development: &development
  host: localhost
  adapter: postgresql
  encoding: utf8
  database: deploy_app_development
  pool: 5
  username: postgres
  password: <%= ENV['DATABASE_PASSWORD'] %>

test:
  <<: *development
  database: deploy_app_test

production:
  <<: *development
  database: deploy_app_production
