default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

env: &env
  host:     <%= ENV['DB_HOST'] %>
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

development: &development
  <<: *default
  <<: *env

test:
  <<: *default
  <<: *env
  database: <%= ENV['DB_NAME'] %>_test
  
production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
